# Generated by Django 5.0.4 on 2024-06-13 22:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('flight_id', models.CharField(max_length=5)),
                ('flight_carrierCode', models.CharField(max_length=5)),
                ('no_adults', models.IntegerField(default=1)),
                ('departure_location', models.CharField(max_length=50)),
                ('departure_date', models.DateField()),
                ('departure_time', models.CharField(max_length=20)),
                ('arrival_location', models.CharField(max_length=50)),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.CharField(max_length=20)),
                ('passenger_names', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_currency', models.CharField(max_length=5)),
                ('payment_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('hotel_id', models.CharField(max_length=20)),
                ('hotel_name', models.CharField(max_length=255)),
                ('hotel_city', models.CharField(max_length=5)),
                ('no_rooms', models.IntegerField(default=1)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_currency', models.CharField(max_length=5)),
                ('payment_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
