# Generated by Django 5.0.4 on 2024-06-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_booking',
            name='payer_id',
            field=models.CharField(default='Not Available', max_length=30),
        ),
        migrations.AddField(
            model_name='flight_booking',
            name='payment_id',
            field=models.CharField(default='Not Available', max_length=30),
        ),
        migrations.AddField(
            model_name='hotel_booking',
            name='payer_id',
            field=models.CharField(default='Not Available', max_length=30),
        ),
        migrations.AddField(
            model_name='hotel_booking',
            name='payment_id',
            field=models.CharField(default='Not Available', max_length=30),
        ),
    ]
